// flow-typed signature: 6c18e31e05cd414af9f3d30c139e665c
// flow-typed version: <<STUB>>/cookie-session_v^2.0.0-rc.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cookie-session'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cookie-session' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'cookie-session/index' {
  declare module.exports: $Exports<'cookie-session'>;
}
declare module 'cookie-session/index.js' {
  declare module.exports: $Exports<'cookie-session'>;
}
