// flow-typed signature: 0f5448c80bfba9659dfbc04269e00bca
// flow-typed version: <<STUB>>/eslint-plugin-jsx-control-statements_v^2.2.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jsx-control-statements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jsx-control-statements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-choose-not-empty' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-for-require-each' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-for-require-of' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-if-require-condition' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-jcs-no-undef' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-otherwise-once-last' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-use-if-tag' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-when-require-condition' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-control-statements/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jsx-control-statements/index' {
  declare module.exports: $Exports<'eslint-plugin-jsx-control-statements'>;
}
declare module 'eslint-plugin-jsx-control-statements/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-control-statements'>;
}
declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-choose-not-empty.js' {
  declare module.exports: $Exports<
    'eslint-plugin-jsx-control-statements/lib/rules/jsx-choose-not-empty',
  >;
}
declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-for-require-each.js' {
  declare module.exports: $Exports<
    'eslint-plugin-jsx-control-statements/lib/rules/jsx-for-require-each',
  >;
}
declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-for-require-of.js' {
  declare module.exports: $Exports<
    'eslint-plugin-jsx-control-statements/lib/rules/jsx-for-require-of',
  >;
}
declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-if-require-condition.js' {
  declare module.exports: $Exports<
    'eslint-plugin-jsx-control-statements/lib/rules/jsx-if-require-condition',
  >;
}
declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-jcs-no-undef.js' {
  declare module.exports: $Exports<
    'eslint-plugin-jsx-control-statements/lib/rules/jsx-jcs-no-undef',
  >;
}
declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-otherwise-once-last.js' {
  declare module.exports: $Exports<
    'eslint-plugin-jsx-control-statements/lib/rules/jsx-otherwise-once-last',
  >;
}
declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-use-if-tag.js' {
  declare module.exports: $Exports<
    'eslint-plugin-jsx-control-statements/lib/rules/jsx-use-if-tag',
  >;
}
declare module 'eslint-plugin-jsx-control-statements/lib/rules/jsx-when-require-condition.js' {
  declare module.exports: $Exports<
    'eslint-plugin-jsx-control-statements/lib/rules/jsx-when-require-condition',
  >;
}
declare module 'eslint-plugin-jsx-control-statements/lib/utils.js' {
  declare module.exports: $Exports<
    'eslint-plugin-jsx-control-statements/lib/utils',
  >;
}
