export const UPDATE_EDITOR_STATE = 'UPDATE_EDITOR_STATE';
export const DELETE_EDITOR_STATE = 'DELETE_EDITOR_STATE';
export const CREATE_NEW_DRAFT_SUBMIT = 'CREATE_NEW_DRAFT_SUBMIT';
export const CREATE_NEW_DRAFT_SUCCSS = 'CREATE_NEW_DRAFT_SUCCSS';
